apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskapp
  name: flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskapp
    spec:
      containers:
        - image: 840448912054.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/flask_test:47
          name: flaskapp
          resources: {}
status: {}
